### PR TITLE
Revise Assignment Week 02

### PR DESCRIPTION
**Pull request by sherenyang**
I have updated the assignments as follows:
- Assignment 5:
Number 11 and 12: ConcurrentModificationException issue (when modifying a list while traversing it).

- Assignment 6:
Number 3: Defined key fields based on the start index and end index.

Additionally, I have reorganized the folders, naming them according to the number of exercises, as per your feedback. Could you please review it once more? Thank you for your guidance.

### CODE REVIEW

**Review by helenhash — CHANGES_REQUESTED** [review]
Overall, it's quite good.
Fix on feedback for Assignment 5 is good.
Assignment 6: i dont see the update for start and end index like a param.

I see that you PR for review week 2, also include week 3, any reason?

**Comment by sherenyang** [comment]
> Overall, it's quite good. Fix on feedback for Assignment 5 is good. Assignment 6: i dont see the update for start and end index like a param.
> 
> I see that you PR for review week 2, also include week 3, any reason?

Thank you for your feedback!

I have updated assignment 6 based on your feedback. Is that already alright? I also have removed Week 3 in my PR. Sorry for the inconvenience before.

Thank you for your guidance.

**Comment by helenhash** [comment]
@sherenyang it's good. You can merge this PR to main to mark as finish this assignment.

**Comment by sherenyang** [comment]
> @sherenyang it's good. You can merge this PR to main to mark as finish this assignment.

Alright, miss. Thank you so much for the review and guidance!

**Pull request merged**
